source 'https://rubygems.org'

gem "jekyll", "~> 4.0.0"
gem "minima", "~> 2.2"

group :development do
  gem 'popper_js', '>= 1.12.3'
end

group :debug do
  gem 'byebug', platforms: [:mri], require: false
end
